// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD18O4oEbib_QDYqP6U1M0nKrOyCaTaWaw',
    appId: '1:852940351541:web:2cbe795f516e801cbe697c',
    messagingSenderId: '852940351541',
    projectId: 'concordemobileapp',
    authDomain: 'concordemobileapp.firebaseapp.com',
    storageBucket: 'concordemobileapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDTfH1ykzd5rZCiSeX9a4g6KBzvqASeW8',
    appId: '1:852940351541:android:a0a9da583c601b44be697c',
    messagingSenderId: '852940351541',
    projectId: 'concordemobileapp',
    storageBucket: 'concordemobileapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEEyFNcCkhthhJLa1Xiz0NRiydnNN2b_8',
    appId: '1:852940351541:ios:e9f3e5b8bc0ae8e3be697c',
    messagingSenderId: '852940351541',
    projectId: 'concordemobileapp',
    storageBucket: 'concordemobileapp.appspot.com',
    iosClientId: '852940351541-el04nnkm6v9g3ajmnrarrmbouo11v1mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.concordeappfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEEyFNcCkhthhJLa1Xiz0NRiydnNN2b_8',
    appId: '1:852940351541:ios:13700b2f27342f18be697c',
    messagingSenderId: '852940351541',
    projectId: 'concordemobileapp',
    storageBucket: 'concordemobileapp.appspot.com',
    iosClientId: '852940351541-82rvqu308iblg1l8qcdf9v2ha82tk8qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.concordeappfinal.RunnerTests',
  );
}
