// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC74aroWzUGvCFb0uc5c6ROmlaTk6ghWoA',
    appId: '1:718646568759:web:24e6f2a8c3e3f3146b1cb2',
    messagingSenderId: '718646568759',
    projectId: 'mobile-app-final-cr7',
    authDomain: 'mobile-app-final-cr7.firebaseapp.com',
    storageBucket: 'mobile-app-final-cr7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDhVLJ6PQYpQrz5U4N7IjjyuDWbmF8XIQ',
    appId: '1:718646568759:android:c21cf6e998e377946b1cb2',
    messagingSenderId: '718646568759',
    projectId: 'mobile-app-final-cr7',
    storageBucket: 'mobile-app-final-cr7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPAcPfOXceg5nMP8sK5LpGjYMwrWmKdWY',
    appId: '1:718646568759:ios:0686a6d5187124616b1cb2',
    messagingSenderId: '718646568759',
    projectId: 'mobile-app-final-cr7',
    storageBucket: 'mobile-app-final-cr7.appspot.com',
    iosClientId: '718646568759-3ur481cieb64rrb46fneba680a2la4t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.concordeappfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPAcPfOXceg5nMP8sK5LpGjYMwrWmKdWY',
    appId: '1:718646568759:ios:012bf6217bedf8216b1cb2',
    messagingSenderId: '718646568759',
    projectId: 'mobile-app-final-cr7',
    storageBucket: 'mobile-app-final-cr7.appspot.com',
    iosClientId: '718646568759-cp1jtjjmr2hjbs4c2oftc15shfobttnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.concordeappfinal.RunnerTests',
  );
}
